
version: 2.1

jobs:  
  
  configure_infrastructure:
    docker:
      - image:  python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["41:c1:8c:43:5c:6f:fe:30:51:9d:1f:ee:86:e6:89:6f"]
      - run: 
          name: Install Ansible
          command:  |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command:  |
            ansible-playbook -i inventory.txt main.yml
              
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
