---
- name: "update yum packages"
  become: true
  yum:
    update_cache: yes

- name: "upgrade packages"
  become: true
  yum:  
    update_only:  yes
  
- name: "install dependencies to install nodejs"
  become: true
  shell:  
    curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash - 

- name: "install dependencies to install nodejs"
  become: true
  yum:
    name: ["gcc-c++", "make"]
    state:  latest

- name: "install NodeJS"
  become: true
  yum:
    name: [nodejs]
    state:  latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state:  present

- name: "create a ~/web directory"
  become: true
  file:
    path: ~/web 
    state:  directory

- name: "Copy index test page"
  template:
    src:  files/index.js
    dest: ~/web/index.js

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f